version: "3"
services:
  backend:
    build: .
    restart: on-failure
    environment:
      - DJANGO_SECRET_KEY=secret123
      - DEBUG=1
      - ALLOWED_HOSTS=*
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/www
    ports:
      - "8000:8000"