version: "3"
services:
  web:
    build: .
    container_name: web01
    env_file:
      - ./.env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db01
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
volumes:
  postgres_database:
    external: true
